// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol AnalyticsHubServiceStub: Sendable {
    func listDataExchanges(
      request: ListDataExchangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListDataExchangesResponse

    func listOrgDataExchanges(
      request: ListOrgDataExchangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListOrgDataExchangesResponse

    func getDataExchange(
      request: GetDataExchangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.DataExchange

    func createDataExchange(
      request: CreateDataExchangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.DataExchange

    func updateDataExchange(
      request: UpdateDataExchangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.DataExchange

    func deleteDataExchange(
      request: DeleteDataExchangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listListings(
      request: ListListingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListListingsResponse

    func getListing(
      request: GetListingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.Listing

    func createListing(
      request: CreateListingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.Listing

    func updateListing(
      request: UpdateListingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.Listing

    func deleteListing(
      request: DeleteListingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func subscribeListing(
      request: SubscribeListingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.SubscribeListingResponse

    func subscribeDataExchange(
      request: SubscribeDataExchangeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func refreshSubscription(
      request: RefreshSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getSubscription(
      request: GetSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.Subscription

    func listSubscriptions(
      request: ListSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListSubscriptionsResponse

    func listSharedResourceSubscriptions(
      request: ListSharedResourceSubscriptionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListSharedResourceSubscriptionsResponse

    func revokeSubscription(
      request: RevokeSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.RevokeSubscriptionResponse

    func deleteSubscription(
      request: DeleteSubscriptionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func createQueryTemplate(
      request: CreateQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.QueryTemplate

    func getQueryTemplate(
      request: GetQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.QueryTemplate

    func listQueryTemplates(
      request: ListQueryTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.ListQueryTemplatesResponse

    func updateQueryTemplate(
      request: UpdateQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.QueryTemplate

    func deleteQueryTemplate(
      request: DeleteQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func submitQueryTemplate(
      request: SubmitQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.QueryTemplate

    func approveQueryTemplate(
      request: ApproveQueryTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryAnalyticsHubV1.QueryTemplate

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
