// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for a BigQuery subscription.
public struct BigQueryConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The name of the table to which to write data, of the form
  /// {projectId}.{datasetId}.{tableId}
  public var table: Swift.String = Swift.String()

  /// Optional. When true, use the topic's schema as the columns to write to in
  /// BigQuery, if it exists. `use_topic_schema` and `use_table_schema` cannot be
  /// enabled at the same time.
  public var useTopicSchema: Swift.Bool = Swift.Bool()

  /// Optional. When true, write the subscription name, message_id, publish_time,
  /// attributes, and ordering_key to additional columns in the table. The
  /// subscription name, message_id, and publish_time fields are put in their own
  /// columns while all other message properties (other than data) are written to
  /// a JSON object in the attributes column.
  public var writeMetadata: Swift.Bool = Swift.Bool()

  /// Optional. When true and use_topic_schema is true, any fields that are a
  /// part of the topic schema that are not part of the BigQuery table schema are
  /// dropped when writing to BigQuery. Otherwise, the schemas must be kept in
  /// sync and any messages with extra fields are not written and remain in the
  /// subscription's backlog.
  public var dropUnknownFields: Swift.Bool = Swift.Bool()

  /// Optional. When true, use the BigQuery table's schema as the columns to
  /// write to in BigQuery. `use_table_schema` and `use_topic_schema` cannot be
  /// enabled at the same time.
  public var useTableSchema: Swift.Bool = Swift.Bool()

  /// Optional. The service account to use to write to BigQuery. The subscription
  /// creator or updater that specifies this field must have
  /// `iam.serviceAccounts.actAs` permission on the service account. If not
  /// specified, the Pub/Sub [service
  /// agent](https://cloud.google.com/iam/docs/service-agents),
  /// service-{project_number}@gcp-sa-pubsub.iam.gserviceaccount.com, is used.
  public var serviceAccountEmail: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigQueryConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryConfig().with { $0.table = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let table = CodingKeys(stringValue: "table")
    static let useTopicSchema = CodingKeys(stringValue: "useTopicSchema")
    static let writeMetadata = CodingKeys(stringValue: "writeMetadata")
    static let dropUnknownFields = CodingKeys(stringValue: "dropUnknownFields")
    static let useTableSchema = CodingKeys(stringValue: "useTableSchema")
    static let serviceAccountEmail = CodingKeys(stringValue: "serviceAccountEmail")

    static let _knownKeys: Set<Swift.String> = [
      "table",
      "useTopicSchema",
      "writeMetadata",
      "dropUnknownFields",
      "useTableSchema",
      "serviceAccountEmail",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .table) {
      self.table = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useTopicSchema) {
      self.useTopicSchema = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .writeMetadata) {
      self.writeMetadata = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dropUnknownFields) {
      self.dropUnknownFields = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useTableSchema) {
      self.useTableSchema = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccountEmail) {
      self.serviceAccountEmail = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.table, forKey: .table)
    try container.encode(self.useTopicSchema, forKey: .useTopicSchema)
    try container.encode(self.writeMetadata, forKey: .writeMetadata)
    try container.encode(self.dropUnknownFields, forKey: .dropUnknownFields)
    try container.encode(self.useTableSchema, forKey: .useTableSchema)
    try container.encode(self.serviceAccountEmail, forKey: .serviceAccountEmail)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.BigQueryConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
