// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A data exchange is a container that lets you share data. Along with the
/// descriptive information about the data exchange, it contains listings that
/// reference shared datasets.
public struct DataExchange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the data exchange.
  /// e.g. `projects/myproject/locations/us/dataExchanges/123`.
  public var name: Swift.String = Swift.String()

  /// Required. Human-readable display name of the data exchange. The display
  /// name must contain only Unicode letters, numbers (0-9), underscores (_),
  /// dashes (-), spaces ( ), ampersands (&) and must not start or end with
  /// spaces. Default value is an empty string. Max length: 63 bytes.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Description of the data exchange. The description must not
  /// contain Unicode non-characters as well as C0 and C1 control codes except
  /// tabs (HT), new lines (LF), carriage returns (CR), and page breaks (FF).
  /// Default value is an empty string.
  /// Max length: 2000 bytes.
  public var description: Swift.String = Swift.String()

  /// Optional. Email or URL of the primary point of contact of the data
  /// exchange. Max Length: 1000 bytes.
  public var primaryContact: Swift.String = Swift.String()

  /// Optional. Documentation describing the data exchange.
  public var documentation: Swift.String = Swift.String()

  /// Output only. Number of listings contained in the data exchange.
  public var listingCount: Swift.Int32 = Swift.Int32()

  /// Optional. Base64 encoded image representing the data exchange. Max
  /// Size: 3.0MiB Expected image dimensions are 512x512 pixels, however the API
  /// only performs validation on size of the encoded data. Note: For byte
  /// fields, the content of the fields are base64-encoded (which increases the
  /// size of the data by 33-36%) when using JSON on the wire.
  public var icon: Foundation.Data = Foundation.Data()

  /// Optional. Configurable data sharing environment option for a data exchange.
  public var sharingEnvironmentConfig: SharingEnvironmentConfig? = nil

  /// Optional. Type of discovery on the discovery page for all the listings
  /// under this exchange. Updating this field also updates (overwrites) the
  /// discovery_type field for all the listings under this exchange.
  public var discoveryType: DiscoveryType? = nil

  /// Optional. By default, false.
  /// If true, the DataExchange has an email sharing mandate enabled.
  public var logLinkedDatasetQueryUserEmail: Swift.Bool? = nil

  /// Initialize a new instance of `DataExchange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataExchange().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.DataExchange"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
