// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Defines the destination bigquery dataset.
public struct DestinationDataset: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A reference that identifies the destination dataset.
  public var datasetReference: DestinationDatasetReference? = nil

  /// Optional. A descriptive name for the dataset.
  public var friendlyName: GoogleWKT.StringValue? = nil

  /// Optional. A user-friendly description of the dataset.
  public var description: GoogleWKT.StringValue? = nil

  /// Optional. The labels associated with this dataset. You can use these
  /// to organize and group your datasets.
  /// You can set this property when inserting or updating a dataset.
  /// See https://cloud.google.com/resource-manager/docs/creating-managing-labels
  /// for more information.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. The geographic location where the dataset should reside. See
  /// https://cloud.google.com/bigquery/docs/locations for supported
  /// locations.
  public var location: Swift.String = Swift.String()

  /// Optional. The geographic locations where the dataset should be replicated.
  /// See [BigQuery locations](https://cloud.google.com/bigquery/docs/locations)
  /// for supported locations.
  public var replicaLocations: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DestinationDataset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DestinationDataset().with { $0.datasetReference = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let datasetReference = CodingKeys(stringValue: "datasetReference")
    static let friendlyName = CodingKeys(stringValue: "friendlyName")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let location = CodingKeys(stringValue: "location")
    static let replicaLocations = CodingKeys(stringValue: "replicaLocations")

    static let _knownKeys: Set<Swift.String> = [
      "datasetReference",
      "friendlyName",
      "description",
      "labels",
      "location",
      "replicaLocations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.datasetReference = try container.decodeIfPresent(
      DestinationDatasetReference.self, forKey: .datasetReference)
    self.friendlyName = try container.decodeIfPresent(
      GoogleWKT.StringValue.self, forKey: .friendlyName)
    self.description = try container.decodeIfPresent(
      GoogleWKT.StringValue.self, forKey: .description)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .replicaLocations) {
      self.replicaLocations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.datasetReference, forKey: .datasetReference)
    try container.encodeIfPresent(self.friendlyName, forKey: .friendlyName)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.replicaLocations, forKey: .replicaLocations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.DestinationDataset"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
