// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// User-defined JavaScript function that can transform or filter a Pub/Sub
/// message.
public struct JavaScriptUDF: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the JavasScript function that should applied to Pub/Sub
  /// messages.
  public var functionName: Swift.String = Swift.String()

  /// Required. JavaScript code that contains a function `function_name` with the
  /// below signature:
  ///
  /// ```
  ///   /**
  ///   * Transforms a Pub/Sub message.
  ///
  ///   * @return {(Object<string, (string | Object<string, string>)>|null)} - To
  ///   * filter a message, return `null`. To transform a message return a map
  ///   * with the following keys:
  ///   *   - (required) 'data' : {string}
  ///   *   - (optional) 'attributes' : {Object<string, string>}
  ///   * Returning empty `attributes` will remove all attributes from the
  ///   * message.
  ///   *
  ///   * @param  {(Object<string, (string | Object<string, string>)>} Pub/Sub
  ///   * message. Keys:
  ///   *   - (required) 'data' : {string}
  ///   *   - (required) 'attributes' : {Object<string, string>}
  ///   *
  ///   * @param  {Object<string, any>} metadata - Pub/Sub message metadata.
  ///   * Keys:
  ///   *   - (required) 'message_id'  : {string}
  ///   *   - (optional) 'publish_time': {string} YYYY-MM-DDTHH:MM:SSZ format
  ///   *   - (optional) 'ordering_key': {string}
  ///   */
  ///
  ///   function <function_name>(message, metadata) {
  ///   }
  /// ```
  public var code: Swift.String = Swift.String()

  /// Initialize a new instance of `JavaScriptUDF`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JavaScriptUDF().with { $0.functionName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.JavaScriptUDF"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
