// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// All supported message transforms types.
public struct MessageTransform: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. This field is deprecated, use the `disabled` field to disable
  /// transforms.
  @available(*, deprecated)
  public var enabled: Swift.Bool = Swift.Bool()

  /// Optional. If true, the transform is disabled and will not be applied to
  /// messages. Defaults to `false`.
  public var disabled: Swift.Bool = Swift.Bool()

  /// The type of transform to apply to messages.
  public var transform: OneOf_Transform? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MessageTransform`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MessageTransform().with { $0.javascriptUdf = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let javascriptUdf = CodingKeys(stringValue: "javascriptUdf")
    static let enabled = CodingKeys(stringValue: "enabled")
    static let disabled = CodingKeys(stringValue: "disabled")

    static let _knownKeys: Set<Swift.String> = [
      "javascriptUdf",
      "enabled",
      "disabled",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
      self.enabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }

    var transform: OneOf_Transform? = nil
    let transformCheckAndSet = {
      if transform != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'transform'"))
      }
      transform = $0
    }
    if let javascriptUdf = try container.decodeIfPresent(
      JavaScriptUDF?.self, forKey: .javascriptUdf)
    {
      try transformCheckAndSet(.javascriptUdf(javascriptUdf))
    }
    self.transform = transform
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enabled, forKey: .enabled)
    try container.encode(self.disabled, forKey: .disabled)

    if let choice = self.transform {
      switch choice {
      case .javascriptUdf(let value):
        try container.encode(value, forKey: .javascriptUdf)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of transform to apply to messages.
  public enum OneOf_Transform: Codable, Equatable, Sendable {
    /// Optional. JavaScript User Defined Function. If multiple JavaScriptUDF's
    /// are specified on a resource, each must have a unique `function_name`.
    indirect case javascriptUdf(JavaScriptUDF?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.MessageTransform"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
