// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for subscribing to a Data Exchange.
public struct SubscribeDataExchangeRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the Data Exchange.
  /// e.g. `projects/publisherproject/locations/us/dataExchanges/123`
  public var name: Swift.String = Swift.String()

  /// Required. The parent resource path of the Subscription.
  /// e.g. `projects/subscriberproject/locations/us`
  public var destination: Swift.String = Swift.String()

  /// Optional. BigQuery destination dataset to create for the subscriber.
  public var destinationDataset: DestinationDataset? = nil

  /// Required. Name of the subscription to create.
  /// e.g. `subscription1`
  public var subscription: Swift.String = Swift.String()

  /// Email of the subscriber.
  public var subscriberContact: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SubscribeDataExchangeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubscribeDataExchangeRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let destination = CodingKeys(stringValue: "destination")
    static let destinationDataset = CodingKeys(stringValue: "destinationDataset")
    static let subscription = CodingKeys(stringValue: "subscription")
    static let subscriberContact = CodingKeys(stringValue: "subscriberContact")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "destination",
      "destinationDataset",
      "subscription",
      "subscriberContact",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destination) {
      self.destination = value
    }
    self.destinationDataset = try container.decodeIfPresent(
      DestinationDataset.self, forKey: .destinationDataset)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subscription) {
      self.subscription = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subscriberContact) {
      self.subscriberContact = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.destination, forKey: .destination)
    try container.encodeIfPresent(self.destinationDataset, forKey: .destinationDataset)
    try container.encode(self.subscription, forKey: .subscription)
    try container.encode(self.subscriberContact, forKey: .subscriberContact)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.SubscribeDataExchangeRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
