// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for subscribing to a listing.
public struct SubscribeListingRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the listing that you want to subscribe to.
  /// e.g. `projects/myproject/locations/us/dataExchanges/123/listings/456`.
  public var name: Swift.String = Swift.String()

  /// Resulting destination of the listing that you subscribed to.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `SubscribeListingRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubscribeListingRequest().with { $0.destinationDataset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case destinationDataset = "destinationDataset"
    case destinationPubsubSubscription = "destinationPubsubSubscription"
    case name = "name"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let destinationDataset = try container.decodeIfPresent(
      DestinationDataset?.self, forKey: .destinationDataset)
    {
      try destinationCheckAndSet(.destinationDataset(destinationDataset))
    }
    if let destinationPubsubSubscription = try container.decodeIfPresent(
      DestinationPubSubSubscription?.self, forKey: .destinationPubsubSubscription)
    {
      try destinationCheckAndSet(.destinationPubsubSubscription(destinationPubsubSubscription))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.destination {
      switch choice {
      case .destinationDataset(let value):
        try container.encode(value, forKey: .destinationDataset)
      case .destinationPubsubSubscription(let value):
        try container.encode(value, forKey: .destinationPubsubSubscription)
      }
    }
  }

  /// Resulting destination of the listing that you subscribed to.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Input only. BigQuery destination dataset to create for the subscriber.
    indirect case destinationDataset(DestinationDataset?)
    /// Input only. Destination Pub/Sub subscription to create for the
    /// subscriber.
    indirect case destinationPubsubSubscription(DestinationPubSubSubscription?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.SubscribeListingRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
