// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A listing is what gets published into a data exchange that a subscriber can
/// subscribe to. It contains a reference to the data source along with
/// descriptive information that will help subscribers find and subscribe the
/// data.
public struct Listing: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the listing.
  /// e.g. `projects/myproject/locations/us/dataExchanges/123/listings/456`
  public var name: Swift.String = Swift.String()

  /// Required. Human-readable display name of the listing. The display name must
  /// contain only Unicode letters, numbers (0-9), underscores (_), dashes (-),
  /// spaces ( ), ampersands (&) and can't start or end with spaces. Default
  /// value is an empty string. Max length: 63 bytes.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Short description of the listing. The description must not
  /// contain Unicode non-characters and C0 and C1 control codes except tabs
  /// (HT), new lines (LF), carriage returns (CR), and page breaks (FF). Default
  /// value is an empty string. Max length: 2000 bytes.
  public var description: Swift.String = Swift.String()

  /// Optional. Email or URL of the primary point of contact of the listing.
  /// Max Length: 1000 bytes.
  public var primaryContact: Swift.String = Swift.String()

  /// Optional. Documentation describing the listing.
  public var documentation: Swift.String = Swift.String()

  /// Output only. Current state of the listing.
  public var state: Listing.State = Listing.State()

  /// Optional. Base64 encoded image representing the listing. Max Size: 3.0MiB
  /// Expected image dimensions are 512x512 pixels, however the API only
  /// performs validation on size of the encoded data.
  /// Note: For byte fields, the contents of the field are base64-encoded (which
  /// increases the size of the data by 33-36%) when using JSON on the wire.
  public var icon: Foundation.Data = Foundation.Data()

  /// Optional. Details of the data provider who owns the source data.
  public var dataProvider: DataProvider? = nil

  /// Optional. Categories of the listing. Up to five categories are allowed.
  public var categories: [Listing.Category] = []

  /// Optional. Details of the publisher who owns the listing and who can share
  /// the source data.
  public var publisher: Publisher? = nil

  /// Optional. Email or URL of the request access of the listing.
  /// Subscribers can use this reference to request access.
  /// Max Length: 1000 bytes.
  public var requestAccess: Swift.String = Swift.String()

  /// Optional. If set, restricted export configuration will be propagated and
  /// enforced on the linked dataset.
  public var restrictedExportConfig: Listing.RestrictedExportConfig? = nil

  /// Optional. If set, stored procedure configuration will be propagated and
  /// enforced on the linked dataset.
  public var storedProcedureConfig: StoredProcedureConfig? = nil

  /// Optional. Type of discovery of the listing on the discovery page.
  public var discoveryType: DiscoveryType? = nil

  /// Output only. Listing shared asset type.
  public var resourceType: SharedResourceType = SharedResourceType()

  /// Output only. Commercial info contains the information about the commercial
  /// data products associated with the listing.
  public var commercialInfo: Listing.CommercialInfo? = nil

  /// Optional. By default, false.
  /// If true, the Listing has an email sharing mandate enabled.
  public var logLinkedDatasetQueryUserEmail: Swift.Bool? = nil

  /// Optional. If true, the listing is only available to get the resource
  /// metadata. Listing is non subscribable.
  public var allowOnlyMetadataSharing: Swift.Bool? = nil

  /// Listing source.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `Listing`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Listing().with { $0.bigqueryDataset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case bigqueryDataset = "bigqueryDataset"
    case pubsubTopic = "pubsubTopic"
    case name = "name"
    case displayName = "displayName"
    case description = "description"
    case primaryContact = "primaryContact"
    case documentation = "documentation"
    case state = "state"
    case icon = "icon"
    case dataProvider = "dataProvider"
    case categories = "categories"
    case publisher = "publisher"
    case requestAccess = "requestAccess"
    case restrictedExportConfig = "restrictedExportConfig"
    case storedProcedureConfig = "storedProcedureConfig"
    case discoveryType = "discoveryType"
    case resourceType = "resourceType"
    case commercialInfo = "commercialInfo"
    case logLinkedDatasetQueryUserEmail = "logLinkedDatasetQueryUserEmail"
    case allowOnlyMetadataSharing = "allowOnlyMetadataSharing"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.primaryContact = try container.decode(Swift.String.self, forKey: .primaryContact)
    self.documentation = try container.decode(Swift.String.self, forKey: .documentation)
    self.state = try container.decode(Listing.State.self, forKey: .state)
    self.icon = try container.decode(Foundation.Data.self, forKey: .icon)
    self.dataProvider = try container.decodeIfPresent(DataProvider.self, forKey: .dataProvider)
    self.categories = try container.decode([Listing.Category].self, forKey: .categories)
    self.publisher = try container.decodeIfPresent(Publisher.self, forKey: .publisher)
    self.requestAccess = try container.decode(Swift.String.self, forKey: .requestAccess)
    self.restrictedExportConfig = try container.decodeIfPresent(
      Listing.RestrictedExportConfig.self, forKey: .restrictedExportConfig)
    self.storedProcedureConfig = try container.decodeIfPresent(
      StoredProcedureConfig.self, forKey: .storedProcedureConfig)
    self.discoveryType = try container.decodeIfPresent(DiscoveryType.self, forKey: .discoveryType)
    self.resourceType = try container.decode(SharedResourceType.self, forKey: .resourceType)
    self.commercialInfo = try container.decodeIfPresent(
      Listing.CommercialInfo.self, forKey: .commercialInfo)
    self.logLinkedDatasetQueryUserEmail = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .logLinkedDatasetQueryUserEmail)
    self.allowOnlyMetadataSharing = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .allowOnlyMetadataSharing)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let bigqueryDataset = try container.decodeIfPresent(
      Listing.BigQueryDatasetSource?.self, forKey: .bigqueryDataset)
    {
      try sourceCheckAndSet(.bigqueryDataset(bigqueryDataset))
    }
    if let pubsubTopic = try container.decodeIfPresent(
      Listing.PubSubTopicSource?.self, forKey: .pubsubTopic)
    {
      try sourceCheckAndSet(.pubsubTopic(pubsubTopic))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.primaryContact, forKey: .primaryContact)
    try container.encode(self.documentation, forKey: .documentation)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.icon, forKey: .icon)
    try container.encode(self.dataProvider, forKey: .dataProvider)
    try container.encode(self.categories, forKey: .categories)
    try container.encode(self.publisher, forKey: .publisher)
    try container.encode(self.requestAccess, forKey: .requestAccess)
    try container.encode(self.restrictedExportConfig, forKey: .restrictedExportConfig)
    try container.encode(self.storedProcedureConfig, forKey: .storedProcedureConfig)
    try container.encode(self.discoveryType, forKey: .discoveryType)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.commercialInfo, forKey: .commercialInfo)
    try container.encode(
      self.logLinkedDatasetQueryUserEmail, forKey: .logLinkedDatasetQueryUserEmail)
    try container.encode(self.allowOnlyMetadataSharing, forKey: .allowOnlyMetadataSharing)

    if let choice = self.source {
      switch choice {
      case .bigqueryDataset(let value):
        try container.encode(value, forKey: .bigqueryDataset)
      case .pubsubTopic(let value):
        try container.encode(value, forKey: .pubsubTopic)
      }
    }
  }

  /// A reference to a shared dataset. It is an existing BigQuery dataset with a
  /// collection of objects such as tables and views that you want to share
  /// with subscribers.
  /// When subscriber's subscribe to a listing, Analytics Hub creates a linked
  /// dataset in
  /// the subscriber's project. A Linked dataset is an opaque, read-only BigQuery
  /// dataset that serves as a _symbolic link_ to a shared dataset.
  public struct BigQueryDatasetSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Resource name of the dataset source for this listing.
    /// e.g. `projects/myproject/datasets/123`
    public var dataset: Swift.String = Swift.String()

    /// Optional. Resource in this dataset that is selectively shared.
    /// This field is required for data clean room exchanges.
    public var selectedResources: [Listing.BigQueryDatasetSource.SelectedResource] = []

    /// Optional. If set, restricted export policy will be propagated and
    /// enforced on the linked dataset.
    public var restrictedExportPolicy: Listing.BigQueryDatasetSource.RestrictedExportPolicy? = nil

    /// Optional. A list of regions where the publisher has created shared
    /// dataset replicas.
    public var replicaLocations: [Swift.String] = []

    /// Output only. Server-owned effective state of replicas.
    /// Contains both primary and secondary replicas.
    /// Each replica includes a system-computed (output-only) state and primary
    /// designation.
    public var effectiveReplicas: [Listing.BigQueryDatasetSource.Replica] = []

    /// Initialize a new instance of `BigQueryDatasetSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryDatasetSource().with { $0.dataset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Resource in this dataset that is selectively shared.
    public struct SelectedResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      public var resource: OneOf_Resource? = nil

      /// Initialize a new instance of `SelectedResource`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SelectedResource().with { $0.table = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case table = "table"
        case routine = "routine"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var resource: OneOf_Resource? = nil
        let resourceCheckAndSet = {
          if resource != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'resource'"))
          }
          resource = $0
        }
        if let table = try container.decodeIfPresent(Swift.String.self, forKey: .table) {
          try resourceCheckAndSet(.table(table))
        }
        if let routine = try container.decodeIfPresent(Swift.String.self, forKey: .routine) {
          try resourceCheckAndSet(.routine(routine))
        }
        self.resource = resource
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.resource {
          switch choice {
          case .table(let value):
            try container.encode(value, forKey: .table)
          case .routine(let value):
            try container.encode(value, forKey: .routine)
          }
        }
      }

      public enum OneOf_Resource: Codable, Equatable, Sendable {
        /// Optional. Format:
        /// For table:
        /// `projects/{projectId}/datasets/{datasetId}/tables/{tableId}`
        /// Example:"projects/test_project/datasets/test_dataset/tables/test_table"
        case table(Swift.String)
        /// Optional. Format:
        /// For routine:
        /// `projects/{projectId}/datasets/{datasetId}/routines/{routineId}`
        /// Example:"projects/test_project/datasets/test_dataset/routines/test_routine"
        case routine(Swift.String)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.BigQueryDatasetSource.SelectedResource"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Restricted export policy used to configure restricted export on linked
    /// dataset.
    public struct RestrictedExportPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. If true, enable restricted export.
      public var enabled: GoogleCloudWkt.BoolValue? = nil

      /// Optional. If true, restrict direct table access (read
      /// api/tabledata.list) on linked table.
      public var restrictDirectTableAccess: GoogleCloudWkt.BoolValue? = nil

      /// Optional. If true, restrict export of query result derived from
      /// restricted linked dataset table.
      public var restrictQueryResult: GoogleCloudWkt.BoolValue? = nil

      /// Initialize a new instance of `RestrictedExportPolicy`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RestrictedExportPolicy().with { $0.enabled = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.BigQueryDatasetSource.RestrictedExportPolicy"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Represents the state of a replica of a shared dataset.
    /// It includes the geographic location of the replica and
    /// system-computed, output-only fields indicating its replication state and
    /// whether it is the primary replica.
    public struct Replica: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. The geographic location where the replica resides. See
      /// [BigQuery locations](https://cloud.google.com/bigquery/docs/locations)
      /// for supported locations. Eg. "us-central1".
      public var location: Swift.String = Swift.String()

      /// Output only. Assigned by Analytics Hub based on real BigQuery
      /// replication state.
      public var replicaState: Listing.BigQueryDatasetSource.Replica.ReplicaState = Listing
        .BigQueryDatasetSource.Replica.ReplicaState()

      /// Output only. Indicates that this replica is the primary replica.
      public var primaryState: Listing.BigQueryDatasetSource.Replica.PrimaryState? = nil

      /// Initialize a new instance of `Replica`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Replica().with { $0.location = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Replica state of the shared dataset.
      public enum ReplicaState: Codable, Equatable, Sendable {
        /// Default value. This value is unused.
        case unspecified
        /// The replica is backfilled and ready to use.
        case readyToUse
        /// The replica is unavailable, does not exist, or has not been
        /// backfilled yet.
        case unavailable
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .readyToUse: return 1
          case .unavailable: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "REPLICA_STATE_UNSPECIFIED"
          case .readyToUse: return "READY_TO_USE"
          case .unavailable: return "UNAVAILABLE"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReplicaState/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "REPLICA_STATE_UNSPECIFIED": self = .unspecified
          case "READY_TO_USE": self = .readyToUse
          case "UNAVAILABLE": self = .unavailable
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReplicaState/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .readyToUse
          case 2: self = .unavailable
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .readyToUse: return try container.encode(1)
          case .unavailable: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      /// Primary state of the replica. Set only for the primary replica.
      public enum PrimaryState: Codable, Equatable, Sendable {
        /// Default value. This value is unused.
        case unspecified
        /// The replica is the primary replica.
        case primaryReplica
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .primaryReplica: return 1
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "PRIMARY_STATE_UNSPECIFIED"
          case .primaryReplica: return "PRIMARY_REPLICA"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PrimaryState/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "PRIMARY_STATE_UNSPECIFIED": self = .unspecified
          case "PRIMARY_REPLICA": self = .primaryReplica
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PrimaryState/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .primaryReplica
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .primaryReplica: return try container.encode(1)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.BigQueryDatasetSource.Replica"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.BigQueryDatasetSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Pub/Sub topic source.
  public struct PubSubTopicSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Resource name of the Pub/Sub topic source for this listing.
    /// e.g. projects/myproject/topics/topicId
    public var topic: Swift.String = Swift.String()

    /// Optional. Region hint on where the data might be published. Data affinity
    /// regions are modifiable. See https://cloud.google.com/about/locations for
    /// full listing of possible Cloud regions.
    public var dataAffinityRegions: [Swift.String] = []

    /// Initialize a new instance of `PubSubTopicSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PubSubTopicSource().with { $0.topic = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.PubSubTopicSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Restricted export config, used to configure restricted export on linked
  /// dataset.
  public struct RestrictedExportConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. If true, enable restricted export.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Output only. If true, restrict direct table access(read
    /// api/tabledata.list) on linked table.
    public var restrictDirectTableAccess: Swift.Bool = Swift.Bool()

    /// Optional. If true, restrict export of query result derived from
    /// restricted linked dataset table.
    public var restrictQueryResult: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `RestrictedExportConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RestrictedExportConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.RestrictedExportConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Commercial info contains the information about the commercial data products
  /// associated with the listing.
  public struct CommercialInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Details of the Marketplace Data Product associated with the
    /// Listing.
    public var cloudMarketplace: Listing.CommercialInfo.GoogleCloudMarketplaceInfo? = nil

    /// Initialize a new instance of `CommercialInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CommercialInfo().with { $0.cloudMarketplace = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Specifies the details of the Marketplace Data Product associated with the
    /// Listing.
    public struct GoogleCloudMarketplaceInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. Resource name of the commercial service associated with
      /// the Marketplace Data Product. e.g. example.com
      public var service: Swift.String? = nil

      /// Output only. Commercial state of the Marketplace Data Product.
      public var commercialState:
        Listing.CommercialInfo.GoogleCloudMarketplaceInfo.CommercialState? = nil

      /// Initialize a new instance of `GoogleCloudMarketplaceInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GoogleCloudMarketplaceInfo().with { $0.service = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Indicates whether this commercial access is currently active.
      public enum CommercialState: Codable, Equatable, Sendable {
        /// Commercialization is incomplete and cannot be used.
        case unspecified
        /// Commercialization has been initialized.
        case onboarding
        /// Commercialization is complete and available for use.
        case active
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .onboarding: return 1
          case .active: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "COMMERCIAL_STATE_UNSPECIFIED"
          case .onboarding: return "ONBOARDING"
          case .active: return "ACTIVE"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommercialState/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "COMMERCIAL_STATE_UNSPECIFIED": self = .unspecified
          case "ONBOARDING": self = .onboarding
          case "ACTIVE": self = .active
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommercialState/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .onboarding
          case 2: self = .active
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .onboarding: return try container.encode(1)
          case .active: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.CommercialInfo.GoogleCloudMarketplaceInfo"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing.CommercialInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State of the listing.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Subscribable state. Users with dataexchange.listings.subscribe permission
    /// can subscribe to this listing.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Listing categories.
  public enum Category: Codable, Equatable, Sendable {
    case unspecified
    case others
    case advertisingAndMarketing
    case commerce
    case climateAndEnvironment
    case demographics
    case economics
    case education
    case energy
    case financial
    case gaming
    case geospatial
    case healthcareAndLifeScience
    case media
    case publicSector
    case retail
    case sports
    case scienceAndResearch
    case transportationAndLogistics
    case travelAndTourism
    case googleEarthEngine
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .others: return 1
      case .advertisingAndMarketing: return 2
      case .commerce: return 3
      case .climateAndEnvironment: return 4
      case .demographics: return 5
      case .economics: return 6
      case .education: return 7
      case .energy: return 8
      case .financial: return 9
      case .gaming: return 10
      case .geospatial: return 11
      case .healthcareAndLifeScience: return 12
      case .media: return 13
      case .publicSector: return 14
      case .retail: return 15
      case .sports: return 16
      case .scienceAndResearch: return 17
      case .transportationAndLogistics: return 18
      case .travelAndTourism: return 19
      case .googleEarthEngine: return 20
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATEGORY_UNSPECIFIED"
      case .others: return "CATEGORY_OTHERS"
      case .advertisingAndMarketing: return "CATEGORY_ADVERTISING_AND_MARKETING"
      case .commerce: return "CATEGORY_COMMERCE"
      case .climateAndEnvironment: return "CATEGORY_CLIMATE_AND_ENVIRONMENT"
      case .demographics: return "CATEGORY_DEMOGRAPHICS"
      case .economics: return "CATEGORY_ECONOMICS"
      case .education: return "CATEGORY_EDUCATION"
      case .energy: return "CATEGORY_ENERGY"
      case .financial: return "CATEGORY_FINANCIAL"
      case .gaming: return "CATEGORY_GAMING"
      case .geospatial: return "CATEGORY_GEOSPATIAL"
      case .healthcareAndLifeScience: return "CATEGORY_HEALTHCARE_AND_LIFE_SCIENCE"
      case .media: return "CATEGORY_MEDIA"
      case .publicSector: return "CATEGORY_PUBLIC_SECTOR"
      case .retail: return "CATEGORY_RETAIL"
      case .sports: return "CATEGORY_SPORTS"
      case .scienceAndResearch: return "CATEGORY_SCIENCE_AND_RESEARCH"
      case .transportationAndLogistics: return "CATEGORY_TRANSPORTATION_AND_LOGISTICS"
      case .travelAndTourism: return "CATEGORY_TRAVEL_AND_TOURISM"
      case .googleEarthEngine: return "CATEGORY_GOOGLE_EARTH_ENGINE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Category/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATEGORY_UNSPECIFIED": self = .unspecified
      case "CATEGORY_OTHERS": self = .others
      case "CATEGORY_ADVERTISING_AND_MARKETING": self = .advertisingAndMarketing
      case "CATEGORY_COMMERCE": self = .commerce
      case "CATEGORY_CLIMATE_AND_ENVIRONMENT": self = .climateAndEnvironment
      case "CATEGORY_DEMOGRAPHICS": self = .demographics
      case "CATEGORY_ECONOMICS": self = .economics
      case "CATEGORY_EDUCATION": self = .education
      case "CATEGORY_ENERGY": self = .energy
      case "CATEGORY_FINANCIAL": self = .financial
      case "CATEGORY_GAMING": self = .gaming
      case "CATEGORY_GEOSPATIAL": self = .geospatial
      case "CATEGORY_HEALTHCARE_AND_LIFE_SCIENCE": self = .healthcareAndLifeScience
      case "CATEGORY_MEDIA": self = .media
      case "CATEGORY_PUBLIC_SECTOR": self = .publicSector
      case "CATEGORY_RETAIL": self = .retail
      case "CATEGORY_SPORTS": self = .sports
      case "CATEGORY_SCIENCE_AND_RESEARCH": self = .scienceAndResearch
      case "CATEGORY_TRANSPORTATION_AND_LOGISTICS": self = .transportationAndLogistics
      case "CATEGORY_TRAVEL_AND_TOURISM": self = .travelAndTourism
      case "CATEGORY_GOOGLE_EARTH_ENGINE": self = .googleEarthEngine
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Category/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .others
      case 2: self = .advertisingAndMarketing
      case 3: self = .commerce
      case 4: self = .climateAndEnvironment
      case 5: self = .demographics
      case 6: self = .economics
      case 7: self = .education
      case 8: self = .energy
      case 9: self = .financial
      case 10: self = .gaming
      case 11: self = .geospatial
      case 12: self = .healthcareAndLifeScience
      case 13: self = .media
      case 14: self = .publicSector
      case 15: self = .retail
      case 16: self = .sports
      case 17: self = .scienceAndResearch
      case 18: self = .transportationAndLogistics
      case 19: self = .travelAndTourism
      case 20: self = .googleEarthEngine
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .others: return try container.encode(1)
      case .advertisingAndMarketing: return try container.encode(2)
      case .commerce: return try container.encode(3)
      case .climateAndEnvironment: return try container.encode(4)
      case .demographics: return try container.encode(5)
      case .economics: return try container.encode(6)
      case .education: return try container.encode(7)
      case .energy: return try container.encode(8)
      case .financial: return try container.encode(9)
      case .gaming: return try container.encode(10)
      case .geospatial: return try container.encode(11)
      case .healthcareAndLifeScience: return try container.encode(12)
      case .media: return try container.encode(13)
      case .publicSector: return try container.encode(14)
      case .retail: return try container.encode(15)
      case .sports: return try container.encode(16)
      case .scienceAndResearch: return try container.encode(17)
      case .transportationAndLogistics: return try container.encode(18)
      case .travelAndTourism: return try container.encode(19)
      case .googleEarthEngine: return try container.encode(20)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Listing source.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Shared dataset i.e. BigQuery dataset source.
    indirect case bigqueryDataset(Listing.BigQueryDatasetSource?)
    /// Pub/Sub topic source.
    indirect case pubsubTopic(Listing.PubSubTopicSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.Listing"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
