// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for listing subscriptions.
public struct ListSubscriptionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource path of the subscription.
  /// e.g. projects/myproject/locations/us
  public var parent: Swift.String = Swift.String()

  /// An expression for filtering the results of the request. Eligible
  /// fields for filtering are:
  ///
  ///  + `listing`
  ///  + `data_exchange`
  ///
  /// Alternatively, a literal wrapped in double quotes may be provided.
  /// This will be checked for an exact match against both fields above.
  ///
  /// In all cases, the full Data Exchange or Listing resource name must
  /// be provided. Some example of using filters:
  ///
  ///  + data_exchange="projects/myproject/locations/us/dataExchanges/123"
  ///  + listing="projects/123/locations/us/dataExchanges/456/listings/789"
  ///  + "projects/myproject/locations/us/dataExchanges/123"
  public var filter: Swift.String = Swift.String()

  /// The maximum number of results to return in a single response page.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Page token, returned by a previous call.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListSubscriptionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListSubscriptionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.bigquery.analyticshub.v1.ListSubscriptionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
